services:
  animeapi.api:
    image: ${DOCKER_REGISTRY-}animeapiapi
    build:
      context: .
      dockerfile: AnimeAPI.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - animeapinetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - animeapinetwork

volumes:
  sqlvolume:

networks:
  animeapinetwork:
